---
- name: Deploy remotefs on Linux
  hosts: filesystem_hosts
  gather_facts: false
  become: true
  vars:
    remote_fs_platform: linux
  tasks:
    - name: Install and configure remotefs
      ansible.builtin.import_tasks: ../tasks/unix-install.yml
