# Homebrew formula for the mightymorgs/homebrew-tap repository.
# Copy to Formula/remotefs.rb in that tap; see packaging/RELEASING.md.
class Remotefs < Formula
  include Language::Python::Virtualenv

  desc "Browse local, SMB and NFS storage over HTTP from another machine"
  homepage "https://github.com/mightymorgs/remote-fs-browser"
  # `brew audit` insists on the long hashed "Source" URL shown on
  # https://pypi.org/project/remote-fs-browser/#files once 0.2.0 is published;
  # this short form resolves to the same file until then.
  url "https://files.pythonhosted.org/packages/source/r/remote-fs-browser/remote_fs_browser-0.2.0.tar.gz"
  sha256 "TODO"
  license "MIT"

  depends_on "rust" => :build # cryptography (via smbprotocol) builds from source
  depends_on "libnfs"
  depends_on "python@3.12"

  # Resource blocks are generated by `brew update-python-resources remotefs`.
  # Run it after every version bump and paste the output here.

  def install
    virtualenv_install_with_resources
  end

  service do
    run [opt_bin/"remotefs", "serve"]
    keep_alive true
    log_path var/"log/remotefs.log"
    error_log_path var/"log/remotefs.log"
    environment_variables LIBNFS_LIBRARY: HOMEBREW_PREFIX/"lib/libnfs.dylib"
  end

  test do
    assert_includes shell_output("#{bin}/remotefs --version"), "remotefs"
  end
end
