# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: mightymorgs.remotefs
PackageVersion: 0.3.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: remotefs/remotefs.exe
    PortableCommandAlias: remotefs
Commands:
  - remotefs
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mightymorgs/remote-fs-browser/releases/download/v0.3.0/remotefs-0.3.0-windows-x64.zip
    InstallerSha256: F2A8EBD43CEC066C3719B71F29546C9C26859E7021DBEAD86950562B94F7D762
ManifestType: installer
ManifestVersion: 1.6.0
